// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCQAzuf97Az0dmIzWztVKuw1lJXh5TfHL0',
    appId: '1:363310110181:web:18afc21bf1c3e9c3a8cb0c',
    messagingSenderId: '363310110181',
    projectId: 'moodapp-a370e',
    authDomain: 'moodapp-a370e.firebaseapp.com',
    storageBucket: 'moodapp-a370e.appspot.com',
    measurementId: 'G-1KT8ZR4HT7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCjRXbNtlmowAA20TYnkXE2iJkqP0fLUpk',
    appId: '1:363310110181:android:b211a959c0b7d582a8cb0c',
    messagingSenderId: '363310110181',
    projectId: 'moodapp-a370e',
    storageBucket: 'moodapp-a370e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDtPsvGi9_CJeALSHhEUXbOliOdBh0UyuE',
    appId: '1:363310110181:ios:a39fcfd21729c661a8cb0c',
    messagingSenderId: '363310110181',
    projectId: 'moodapp-a370e',
    storageBucket: 'moodapp-a370e.appspot.com',
    iosBundleId: 'com.example.flutterMood',
  );
}
